Traceback (most recent call last):
  File "g:/git/src/main.py", line 54, in cr_report_dir
    os.mkdir(dir)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:/Users/Administrator/Desktop/测试数据表/test/b'
2020-09-07 15:49:42.002200-------------------------Traceback (most recent call last):
  File "g:/git/src/main.py", line 54, in cr_report_dir
    os.mkdir(dir)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:/Users/Administrator/Desktop/测试数据表/test/b'
2020-09-07 15:49:42.002200-------------------------Traceback (most recent call last):
  File "g:/git/src/main.py", line 54, in cr_report_dir
    os.mkdir(dir)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:/Users/Administrator/Desktop/测试数据表/test/b'
2020-09-07 15:49:42.002200-------------------------Traceback (most recent call last):
  File "g:/git/src/main.py", line 54, in cr_report_dir
    os.mkdir(dir)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:/Users/Administrator/Desktop/测试数据表/test/b'
2020-09-07 15:49:42.002200-------------------------Traceback (most recent call last):
  File "g:/git/src/main.py", line 54, in cr_report_dir
    os.mkdir(dir)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:/Users/Administrator/Desktop/测试数据表/test/b'
2020-09-07 15:55:41.588200-------------------------Traceback (most recent call last):
  File "g:/git/src/main.py", line 54, in cr_report_dir
    os.mkdir(dir)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:/Users/Administrator/Desktop/测试数据表/test/b'
2020-09-07 15:55:41.588200-------------------------Traceback (most recent call last):
  File "g:/git/src/main.py", line 54, in cr_report_dir
    os.mkdir(dir)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:/Users/Administrator/Desktop/测试数据表/test/b'
2020-09-07 15:59:25.799200-------------------------Traceback (most recent call last):
  File "g:/git/src/main.py", line 54, in cr_report_dir
    os.mkdir(dir)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:/Users/Administrator/Desktop/测试数据表/test/b'
2020-09-07 15:59:38.379200-------------------------Traceback (most recent call last):
  File "g:/git/src/main.py", line 54, in cr_report_dir
    os.mkdir(dir)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:/Users/Administrator/Desktop/测试数据表/test/b'
2020-09-07 16:10:14.556200-------------------------