Traceback (most recent call last):
  File "g:/git/src/main.py", line 67, in cr_report_dir
    os.mkdir(dir)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'G:\\git\\testCase_report'
2020-09-10 17:23:56.542405-------------------------